import React, { useState } from 'react';
import { useSecurity } from '../context/SecurityContext';
import { api } from '../services/api';
import { Alert } from '../types';
import { RiskBadge } from '../components/common/RiskBadge';
import { AlertTriangle, CheckCircle2, ShieldCheck, Check, Clock, Filter } from 'lucide-react';

export const Alerts: React.FC = () => {
  const { activeAlerts, refreshData } = useSecurity();
  const [allAlerts, setAllAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(false);
  const [severityFilter, setSeverityFilter] = useState<string>('ALL');
  const [statusFilter, setStatusFilter] = useState<string>('ALL');

  React.useEffect(() => {
    loadAlerts();
  }, [severityFilter, statusFilter]);

  const loadAlerts = async () => {
    setLoading(true);
    try {
      const params: any = {};
      if (severityFilter !== 'ALL') params.severity = severityFilter;
      if (statusFilter !== 'ALL') params.status = statusFilter;
      const data = await api.getAlerts(params);
      setAllAlerts(data);
    } finally {
      setLoading(false);
    }
  };

  const handleUpdate = async (id: number, status: 'ACKNOWLEDGED' | 'RESOLVED') => {
    await api.updateAlert(id, status);
    await refreshData();
    await loadAlerts();
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-rose-400" />
            <span>Defensive Incident Alerts & Risk Engine</span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Prioritized threat detections generated by heuristic risk scoring rules and baseline audits.
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-2">
          {/* Status filter */}
          <div className="flex items-center gap-1 p-1 bg-slate-900 border border-slate-800 rounded-md">
            {['ALL', 'NEW', 'ACKNOWLEDGED', 'RESOLVED'].map((st) => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`px-2 py-0.5 text-xs font-mono font-medium rounded transition-colors ${
                  statusFilter === st
                    ? 'bg-slate-800 text-rose-400 shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {st}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Severity Filter Tabs */}
      <div className="flex items-center gap-1.5 overflow-x-auto text-xs font-mono">
        {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => (
          <button
            key={sev}
            onClick={() => setSeverityFilter(sev)}
            className={`px-2.5 py-1 rounded border transition-colors ${
              severityFilter === sev
                ? 'bg-slate-800 text-slate-100 border-slate-600 font-semibold'
                : 'bg-slate-900/60 text-slate-400 border-slate-800 hover:bg-slate-800'
            }`}
          >
            {sev}
          </button>
        ))}
      </div>

      {/* Alerts Grid */}
      <div className="space-y-3">
        {allAlerts.length === 0 ? (
          <div className="p-12 text-center rounded-lg border border-slate-800 bg-slate-900/40 text-slate-500">
            <CheckCircle2 className="w-8 h-8 text-emerald-400 mx-auto mb-2 opacity-70" />
            <p className="text-sm font-medium text-slate-300">No alerts found</p>
            <p className="text-xs text-slate-500 mt-0.5">
              No security alerts match the selected severity and status filters.
            </p>
          </div>
        ) : (
          allAlerts.map((alt) => {
            const isResolved = alt.status === 'RESOLVED';
            const isAcknowledged = alt.status === 'ACKNOWLEDGED';

            return (
              <div
                key={alt.id}
                className={`p-4 rounded-lg border transition-all ${
                  alt.severity === 'CRITICAL'
                    ? 'border-rose-900/60 bg-rose-950/10'
                    : alt.severity === 'HIGH'
                    ? 'border-amber-900/60 bg-amber-950/10'
                    : 'border-slate-800 bg-slate-900/40'
                }`}
              >
                <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                  <div className="space-y-1.5 flex-1">
                    <div className="flex items-center gap-2.5 flex-wrap">
                      <span
                        className={`text-[10px] font-mono uppercase px-2 py-0.5 rounded font-bold border ${
                          alt.severity === 'CRITICAL'
                            ? 'text-rose-300 bg-rose-950 border-rose-800'
                            : alt.severity === 'HIGH'
                            ? 'text-amber-300 bg-amber-950 border-amber-800'
                            : 'text-yellow-300 bg-yellow-950 border-yellow-800'
                        }`}
                      >
                        {alt.severity}
                      </span>

                      <span className="text-[10px] font-mono text-slate-400">
                        TYPE: {alt.alert_type}
                      </span>

                      <RiskBadge score={alt.risk_score} level={alt.severity as any} />

                      {alt.device_name && (
                        <span className="text-xs font-semibold text-slate-300">
                          Target: {alt.device_name}
                        </span>
                      )}
                    </div>

                    <h3 className="text-sm font-bold text-slate-100">{alt.title}</h3>
                    <p className="text-xs text-slate-300 leading-relaxed">{alt.description}</p>

                    {/* Threat Reasons Breakdown */}
                    {alt.reasons_json && alt.reasons_json.length > 0 && (
                      <div className="pt-2">
                        <span className="text-[10px] font-mono uppercase text-slate-500 block mb-1">
                          Heuristic Risk Factors:
                        </span>
                        <div className="flex flex-wrap gap-1.5">
                          {alt.reasons_json.map((r, i) => (
                            <span
                              key={i}
                              className="text-[11px] px-2 py-0.5 rounded bg-slate-950/80 border border-slate-800 text-slate-300"
                            >
                              • {r}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Actions & Timestamp */}
                  <div className="flex sm:flex-col items-center sm:items-end justify-between gap-2 shrink-0">
                    <div className="flex items-center gap-1.5 text-[11px] font-mono text-slate-500">
                      <Clock className="w-3.5 h-3.5" />
                      <span>{new Date(alt.timestamp).toLocaleTimeString()}</span>
                    </div>

                    <div className="flex items-center gap-1.5">
                      {alt.status === 'NEW' && (
                        <button
                          onClick={() => handleUpdate(alt.id, 'ACKNOWLEDGED')}
                          className="px-2.5 py-1 rounded text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition-colors cursor-pointer"
                        >
                          Acknowledge
                        </button>
                      )}

                      {alt.status !== 'RESOLVED' && (
                        <button
                          onClick={() => handleUpdate(alt.id, 'RESOLVED')}
                          className="px-2.5 py-1 rounded text-xs font-semibold bg-emerald-950/60 hover:bg-emerald-900/80 text-emerald-300 border border-emerald-500/30 transition-colors cursor-pointer"
                        >
                          Resolve
                        </button>
                      )}

                      {isResolved && (
                        <span className="text-xs font-mono text-emerald-400 font-semibold px-2 py-1 rounded bg-emerald-950/30 border border-emerald-800/40">
                          RESOLVED
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
